import * as z from "zod";

// Define enums
const ItemTypeEnum = z.enum([
    "multiple-choice",
    "free-response",
    "essay",
]);

const StatusEnum = z.enum([
    "draft",
    "review",
    "approved",
    "archived",
]);

const SecurityLevelEnum = z.enum([
    "standard",
    "secure",
    "highly-secure",
]);

// Define content schema
const ContentSchema = z.object({
    question: z.string().min(1), // .min(1) ensures variables are not an empty string
    options: z.array(z.string()).optional(),
    correctAnswer: z.string().min(1), // TODO check that correctAnswer is one of options if itemType is multiple-choice
    explanation: z.string().min(1),
});

// Define metadata schema
const MetadataSchema = z.object({
    author: z.string().min(1),
    status: StatusEnum,
    tags: z.array(z.string()),
    // created, lastModified, and version will be generated by the storage layer, so they are not required in the input schema
});

const UpdateMetadataSchema = z.object({
    //author: z.string().min(1).optional(), 
    status: StatusEnum.optional(),
    tags: z.array(z.string()).optional(),
    //created: z.number().nonnegative().optional(), 
    //lastModified: z.number().nonnegative().optional(),
    //version: z.number().nonnegative().optional() 
});

// Define the ExamItem schema
export const ExamItemSchema = z.object({
    //id will be generated by the storage layer, so it is not required in the input schema
    subject: z.string().min(1),
    itemType: ItemTypeEnum,
    difficulty: z.number().int().min(1).max(5),
    content: ContentSchema,
    metadata: MetadataSchema,
    securityLevel: SecurityLevelEnum,
});

// Define the UpdateExamItem schema
// Zods deepPartial is depracated, would look for alternative with time
// export const UpdateItemSchema = ExamItemSchema.deepPartial();
export const UpdateExamItemSchema = z.object({
    subject: z.string().min(1).optional(),
    itemType: ItemTypeEnum.optional(),
    difficulty: z.number().int().min(1).max(5).optional(),
    content: ContentSchema.partial().optional(),
    metadata: UpdateMetadataSchema.optional(),
    securityLevel: SecurityLevelEnum.optional(),
});